# Generated by Django 5.2.11 on 2026-02-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Asistencia', 'Asistencia'), ('Tardanza', 'Tardanza'), ('Falta', 'Falta'), ('Hora Extra', 'Hora Extra')], max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='empleados.empleado')),
            ],
        ),
    ]
