# Generated by Django 5.2.11 on 2026-02-26 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_sede_empleado_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Admin', 'Administrador del Sistema'), ('RRHH', 'Recursos Humanos'), ('Empleado', 'Empleado Base')], default='Empleado', max_length=20)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
