# Generated by Django 5.2.11 on 2026-02-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empresa_empleado_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='firmado',
            field=models.BooleanField(default=False),
        ),
    ]
